services:
  - type: web
    name: pdf-to-png-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT
